'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Master_ProdAves

    '''<summary>
    '''rptPlataformas control.
    '''</summary>
    '''<remarks>\r
    '''Auto-generated field.\r
    '''To modify move field declaration from designer file to code-behind file.\r
    '''</remarks>
    Protected WithEvents rptPlataformas As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Menu control.
    '''</summary>
    '''<remarks>\r
    '''Auto-generated field.\r
    '''To modify move field declaration from designer file to code-behind file.\r
    '''</remarks>
    Protected WithEvents Menu As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>\r
    '''Auto-generated field.\r
    '''To modify move field declaration from designer file to code-behind file.\r
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
