'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Nireo_CatEquipos_View

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UPContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPContenido As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''regPId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regPId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''op control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents op As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CveEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CveEstatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''filtroview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtroview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvindexpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvindexpage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB44 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''IMG44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG44 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL44 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB45 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''IMG45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG45 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL45 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LB41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB41 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''IMG41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG41 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL41 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB42 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''IMG42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG42 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL42 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB43 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''IMG43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG43 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL43 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBFiltroGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBFiltroGen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnInvisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInvisible As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblpaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblpaging As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''totreg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totreg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNP11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP11 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNP12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP12 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BTNP13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP13 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNP14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP14 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpe_regId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpe_regId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpe_op control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpe_op As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkshowdata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkshowdata As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkshowdata2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkshowdata2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MPEAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEAlerta As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MPEBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEBody As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BAlertOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BAlertOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BAlertCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BAlertCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MPECaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPECaptura As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCaptura As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMPE_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMPE_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MPEbody_Obs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEbody_Obs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TBNotasE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNotasE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MPEbody_Filtros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEbody_Filtros As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBLF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLF1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLFiltroEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLFiltroEstatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBLF2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLF2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBFiltroProveedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBFiltroProveedor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLF3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLF3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBFiltroMarca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBFiltroMarca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLF4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLF4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBFiltroSerie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBFiltroSerie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MPEBody_Captura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEBody_Captura As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBLC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBIDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBIDE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNombreE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNombreE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBSerieE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBSerieE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBMarcaE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBMarcaE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBModeloE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBModeloE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBProveedorE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBProveedorE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBFecCompraE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBFecCompraE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender9 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''LBLC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCostoE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBCostoE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FTE1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FTE1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''LBLC9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLMonedaE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLMonedaE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBLC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLEstatusE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEstatusE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BTNP16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP16 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNP15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP15 As Global.System.Web.UI.WebControls.Button
End Class
