'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Nireo_UsuariosE_Frm

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UPContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPContenido As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''filtroview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtroview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvindexpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvindexpage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regPId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regPId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CveEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CveEstatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Autor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Autor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PageTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LB_IMG3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_IMG3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LB_LBL3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_LBL3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LB_IMG2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_IMG2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LB_LBL2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_LBL2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SECTitulo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SECTitulo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCodigoD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBCodigoD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBNombreD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNombreD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBEmailD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBEmailD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNomPuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomPuesto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBNomPuestoD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomPuestoD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNomUbicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomUbicacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBNomUbicacionD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomUbicacionD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNomArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBNomAreaD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomAreaD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEstatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TBNomEstatusD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomEstatusD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SECTitulo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SECTitulo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLRol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLRol As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TBNomRolD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNomRolD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBSecUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBSecUsuario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBSecUsuarioD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBSecUsuarioD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBsecPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBsecPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TBsecPasswordD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBsecPasswordD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SECTitulo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SECTitulo3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bar_action control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bar_action As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LB412 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB412 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''IMG412 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG412 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL412 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL412 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptClientes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''SECTitulo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SECTitulo4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBActualizaD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBActualizaD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpe_regId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpe_regId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpe_op control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpe_op As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkshowdata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkshowdata As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkshowdata2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkshowdata2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MPEAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEAlerta As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MPEBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEBody As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BAlertOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BAlertOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BAlertCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BAlertCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MPECaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPECaptura As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCaptura As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMPE_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMPE_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MPEBody_Captura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEBody_Captura As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBLC20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLClientePE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLClientePE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BTNP16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP16 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNP15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP15 As Global.System.Web.UI.WebControls.Button
End Class
