'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Nireo_PredictorWEB_Frm

    '''<summary>
    '''ProgressProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgressProcessing As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''PanelPredictorInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelPredictorInput As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''LabelPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelSpectreFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSpectreFiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FileUploadSpectre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadSpectre As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''LabelModelFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelModelFiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FileUploadModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUploadModel As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''LabelBias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelBias As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxBias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxBias As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LabelSpectreFileNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSpectreFileNames As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelModelFileNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelModelFileNames As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ButtonPredict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPredict As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LinkButtonExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButtonExport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ImageExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageExcel As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LabelExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelExport As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridViewPredictions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewPredictions As Global.System.Web.UI.WebControls.GridView
End Class
