'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Nukaxan_Clientes_Productos_Frm

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''UPContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPContenido As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''filtroview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filtroview As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvindexpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvindexpage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''regPId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regPId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CveEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CveEstatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Autor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Autor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelcontenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelcontenido As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PageTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LB_IMG3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_IMG3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LB_LBL3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_LBL3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LB_IMG2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_IMG2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LB_LBL2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_LBL2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNombreTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNombreTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MenuF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuF As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''Menu_Titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu_Titulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB45 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''IMG45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IMG45 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LBL45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL45 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptProductos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProductos As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''DependenciasM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DependenciasM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpe_regId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpe_regId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mpe_op control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpe_op As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkshowdata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkshowdata As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkshowdata2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkshowdata2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MPEAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEAlerta As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAlerta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MPEBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEBody As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''BAlertOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BAlertOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BAlertCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BAlertCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''MPECaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPECaptura As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlCaptura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCaptura As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblMPE_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMPE_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MPEBody_Captura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPEBody_Captura As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LBLC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LBLC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNombreE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNombreE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCodigoE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBCodigoE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLCategoriaE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLCategoriaE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LBLC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBCodigoALLIXE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBCodigoALLIXE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LBLC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLC6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DDLEstatusE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEstatusE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BTNP16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP16 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTNP15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTNP15 As Global.System.Web.UI.WebControls.Button
End Class
